"""Generate `docs/logs.md` and the files under `docs/reference/` from the code (ADR 0022, C25).

`--check` exits 1 and names the files that differ from what the code produces.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections.abc import Sequence
from pathlib import Path

from ariane import cli, config, logs, review

REFERENCE = Path("docs") / "reference"
NOTICE = "<!-- Generated by scripts/generate_docs.py from the code; do not edit by hand. -->"


def render_cli() -> str:
    """Each command with its usage, arguments and help, from the argument parser."""
    previous = os.environ.get("COLUMNS")
    os.environ["COLUMNS"] = "80"
    try:
        parser = cli._parser()
        blocks = [("ariane", parser.format_help())]
        for action in parser._actions:
            choices = getattr(action, "choices", None)
            if isinstance(choices, dict):
                blocks += [(f"ariane {n}", p.format_help()) for n, p in choices.items()]
    finally:
        if previous is None:
            del os.environ["COLUMNS"]
        else:
            os.environ["COLUMNS"] = previous
    lines = [NOTICE, "", "# Command-line reference", ""]
    for title, text in blocks:
        lines += [f"## `{title}`", "", "```text", text.rstrip(), "```", ""]
    return "\n".join(lines)


def render_schema() -> str:
    return json.dumps(config.SCHEMA, indent=2) + "\n"


def render_review_schema() -> str:
    return json.dumps(review.SCHEMA, indent=2) + "\n"


def render_logs() -> str:
    """Every functional and technical log type, from the declarations in `ariane.logs`."""
    lines = [NOTICE, "", "# Log types", ""]
    for title, intro, declared in (
        ("Functional logs", "Entries of a ticket's journal.", logs.FUNCTIONAL_TYPES),
        ("Technical logs", "Records of the `ariane` logger.", logs.TECHNICAL_TYPES),
    ):
        lines += [
            f"## {title}",
            "",
            intro,
            "",
            "| Identifier | Level | Meaning |",
            "| --- | --- | --- |",
        ]
        lines += [f"| `{t.id}` | {t.level} | {t.meaning} |" for t in declared.values()]
        lines.append("")
    return "\n".join(lines)


def outputs() -> dict[Path, str]:
    return {
        Path("docs") / "logs.md": render_logs(),
        REFERENCE / "cli.md": render_cli(),
        REFERENCE / "ariane.toml.schema.json": render_schema(),
        REFERENCE / "review-answer.schema.json": render_review_schema(),
    }


def differing(root: Path) -> list[Path]:
    found = []
    for relative, text in outputs().items():
        path = root / relative
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != text:
            found.append(relative)
    return found


def main(argv: Sequence[str] | None = None, root: Path | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/reference/.")
    parser.add_argument("--check", action="store_true", help="exit 1 if a file differs")
    args = parser.parse_args(argv)
    root = root or Path(__file__).resolve().parent.parent
    if args.check:
        stale = differing(root)
        for relative in stale:
            print(f"{relative.as_posix()}: differs from the code; run scripts/generate_docs.py")
        return 1 if stale else 0
    for relative, text in outputs().items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {relative.as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
